defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

save_filetypes: "vtk,np"

custom:
  external_monitor_platform:
    name: wandb
    entity: "michaltakac"
    project: "water-tank"
    api_key: "e67b70a695e41d3d00689deba4e87c6b6d4a7cdc" # get your api key from Neptune.ai

scheduler:
  decay_rate: 0.95
  decay_steps: 15000

training:
  rec_results_freq : 200
  rec_constraint_freq: 50000
  max_steps : 1500000

batch_size:
  inlet: 650
  outlet: 650
  no_slip: 5200
  interior: 6000
  integral_continuity: 310